version: '3'
services:
  db:
    image: mongo
    restart: always
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
  express:
    build:
      dockerfile: Dockerfile 
      context: . 
    networks:
      - webnet
    restart: on-failure
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      MONGODB_HOST: db
      MONGODB_PORT: 27017
networks: 
  webnet: 
